version: '3'
services:
  mongo:
    image: mongo
    volumes:
    - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  redis:
    image: redis
    volumes:
    - ./data/redis:/data

  website:
    build: .
    ports:
      - "8000:8080"
    env_file:
      - conf/.env
    depends_on:
      - mongo
      - redis